//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPedidos.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenProducto()
        {
            this.OrdenPedidoProducto = new HashSet<OrdenPedidoProducto>();
        }
    
        public int OrdenID { get; set; }
        public Nullable<int> ProductoID { get; set; }
        public Nullable<decimal> ValorUnitario { get; set; }
        public Nullable<decimal> ValorParcial { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenPedidoProducto> OrdenPedidoProducto { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
