//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPedidos.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenPedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenPedido()
        {
            this.OrdenPedidoProducto = new HashSet<OrdenPedidoProducto>();
        }
    
        public int OrdenPedidoID { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string Estado { get; set; }
        public string DireccionEntrega { get; set; }
        public string Prioridad { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<int> ClienteID { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenPedidoProducto> OrdenPedidoProducto { get; set; }
    }
}
